# Generated by Django 3.2.2 on 2021-05-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_fulfiller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='app_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
